# Entry Points configuration
[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      permanent = true
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

  [entryPoints.k8sApi]
    address = ":6443"

# Enable Traefik dashboard on HTTPS
[api]
  dashboard = true
  insecure = false

# Docker Provider
[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false
  watch = true

# Logging configuration
[log]
  level = "DEBUG"

# Access log configuration
[accessLog]

# ACME Configuration (Let's Encrypt)
[certificatesResolvers.myresolver.acme]
  email = "your-email@example.com"
  storage = "acme.json"
  [certificatesResolvers.myresolver.acme.httpChallenge]
    entryPoint = "web"

# HTTP Routers
[http.routers]
  # API Router
  [http.routers.api]
    entryPoints = ["websecure"]
    service = "api@internal"
    rule = "Host(`load_balancer1.cefaslocalserver.com`)"
    [http.routers.api.tls]
      certResolver = "myresolver"

  # Kubernetes API Router
  [http.routers.k8sApi]
    entryPoints = ["k8sApi"]
    service = "k8sApi"
    rule = "Host(`api.local.cefaslocalserver.com`)"
    [http.routers.k8sApi.tls]
      certResolver = "myresolver"
      [[tls.certificates]]
        certFile = "/etc/traefik/ssl/cefaslocalserver.com.crt"
        keyFile = "/etc/traefik/ssl/cefaslocalserver.com.key"

# HTTP Services
[http.services]
  [http.services.k8sApi.loadBalancer]
    [[http.services.k8sApi.loadBalancer.servers]]
      url = "https://10.17.3.21:6443"
    [[http.services.k8sApi.loadBalancer.servers]]
      url = "https://10.17.3.22:6443"
    [[http.services.k8sApi.loadBalancer.servers]]
      url = "https://10.17.3.23:6443"

# TLS Certificates
[tls]
  [[tls.certificates]]
    certFile = "/etc/traefik/ssl/cefaslocalserver.com.crt"
    keyFile = "/etc/traefik/ssl/cefaslocalserver.com.key"
