[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.tls]
      certFile = "/etc/traefik/ssl/cefaslocalserver.com.crt"
      keyFile = "/etc/traefik/ssl/cefaslocalserver.com.key"

  [entryPoints.k8sApi]
    address = ":6443"
    [entryPoints.k8sApi.tls]
      certFile = "/etc/traefik/ssl/cefaslocalserver.com.crt"
      keyFile = "/etc/traefik/ssl/cefaslocalserver.com.key"

[api]
  dashboard = true
  insecure = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false

[log]
  level = "DEBUG"

[accessLog]

[certificatesResolvers.myresolver.acme]
  email = "your-email@example.com"
  storage = "acme.json"
  [certificatesResolvers.myresolver.acme.httpChallenge]
    entryPoint = "web"

[http.routers]
  [http.routers.api]
    entryPoints = ["websecure"]
    service = "api@internal"
    rule = "Host(`load_balancer1.cefaslocalserver.com`)"
    [http.routers.api.tls]
      certResolver = "myresolver"

  [http.routers.k8sApi]
    entryPoints = ["k8sApi"]
    service = "k8sApi"
    rule = "Host(`api.local.cefaslocalserver.com`)"
    [http.routers.k8sApi.tls]
      certResolver = "myresolver"

[http.services]
  [http.services.k8sApi.loadBalancer]
    [[http.services.k8sApi.loadBalancer.servers]]
      url = "http://10.17.3.21:6443"
    [[http.services.k8sApi.loadBalancer.servers]]
      url = "http://10.17.3.22:6443"
    [[http.services.k8sApi.loadBalancer.servers]]
      url = "http://10.17.3.23:6443"

[tls]
  [[tls.certificates]]
    certFile = "/etc/traefik/ssl/cefaslocalserver.com.crt"
    keyFile = "/etc/traefik/ssl/cefaslocalserver.com.key"