[entryPoints]
  [entryPoints.web]
    address = ":80"
    # Optional redirection from HTTP to HTTPS
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

  [entryPoints.k8sApi]
    address = ":6443"
    [entryPoints.k8sApi.tls]
      certResolver = "myresolver"

[api]
  dashboard = true
  insecure = false  # Ensure the dashboard is only available over HTTPS

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false  # Keep this false to ensure only explicitly defined services are exposed

[log]
  level = "DEBUG"

[accessLog]  # Enable access logs for visibility

[certificatesResolvers.myresolver.acme]
  email = "your-email@example.com"
  storage = "acme.json"
  [certificatesResolvers.myresolver.acme.httpChallenge]
    entryPoint = "web"  # Use web entry point for HTTP challenge

[http.routers]
  [http.routers.api]
    entryPoints = ["websecure"]
    service = "api@internal"
    rule = "Host(`load_balancer1.cefaslocalserver.com`)"
    [http.routers.api.tls]
      certResolver = "myresolver"

  [http.routers.k8sApi]
    entryPoints = ["k8sApi"]
    service = "k8sApi"
    rule = "Host(`api.local.cefaslocalserver.com`)"
    [http.routers.k8sApi.tls]
      certResolver = "myresolver"

[http.services]
  [http.services.k8sApi.loadBalancer]
    [[http.services.k8sApi.loadBalancer.servers]]
      url = "https://10.17.3.21:6443"  # Use HTTPS for API servers
    [[http.services.k8sApi.loadBalancer.servers]]
      url = "https://10.17.3.22:6443"
    [[http.services.k8sApi.loadBalancer.servers]]
      url = "https://10.17.3.23:6443"

[tls]
  [[tls.certificates]]
    certFile = "/etc/traefik/ssl/cefaslocalserver.com.crt"
    keyFile = "/etc/traefik/ssl/cefaslocalserver.com.key"
