# Configuración de Entry Points
[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      permanent = true

  [entryPoints.websecure]
    address = ":443"

  [entryPoints.k8sApi]
    address = ":6443"

# Dashboard de Traefik habilitado
[api]
  dashboard = true

# Configuración del proveedor Docker
[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false
  watch = true

# Configuración de logs
[log]
  level = "DEBUG"

# Configuración del acceso a los logs
[accessLog]

# Configuración del resolutor de certificados ACME (Let's Encrypt)
[certificatesResolvers.myresolver.acme]
  email = "tu-correo@ejemplo.com"
  storage = "/etc/traefik/acme.json"  # Aquí es donde se almacenarán los certificados
  caServer = "https://acme-v02.api.letsencrypt.org/directory"  # Servidor ACME para Let's Encrypt
  [certificatesResolvers.myresolver.acme.httpChallenge]
    entryPoint = "web"  # Usar el desafío HTTP para la validación

# Routers HTTP
[http.routers]
  # Router para el dashboard de Traefik
  [http.routers.api]
    entryPoints = ["websecure"]
    service = "api@internal"
    rule = "Host(`loadbalancer1.cefaslocalserver.com`)"
    [http.routers.api.tls]
      certResolver = "myresolver"

  # Router para la API de Kubernetes
  [http.routers.k8sApi]
    entryPoints = ["k8sApi"]
    service = "k8sApi"
    rule = "Host(`api.local.cefaslocalserver.com`)"
    [http.routers.k8sApi.tls]
      certResolver = "myresolver"
      [[tls.certificates]]
        certFile = "/etc/traefik/ssl/cefaslocalserver.com.crt"
        keyFile = "/etc/traefik/ssl/cefaslocalserver.com.key"

# Servicios HTTP
[http.services]
  [http.services.k8sApi.loadBalancer]
    [[http.services.k8sApi.loadBalancer.servers]]
      url = "https://10.17.3.21:6443"
    [[http.services.k8sApi.loadBalancer.servers]]
      url = "https://10.17.3.22:6443"
    [[http.services.k8sApi.loadBalancer.servers]]
      url = "https://10.17.3.23:6443"

# Configuración de TLS
[tls]
  [[tls.certificates]]
    certFile = "/etc/traefik/ssl/cefaslocalserver.com.crt"
    keyFile = "/etc/traefik/ssl/cefaslocalserver.com.key"